from RcpConnection import *

c = RcpConnection()
c.connectToDefaultServer()
c.loginContext('pw')

c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
c.receiveCommand()
